#!/usr/bin/env bash
#Configure Nginx server to redirect /redirect_me to another page

sudo apt-get update
sudo apt-get install nginx

mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

#Nginx to handle redirection
printf '%s\n' "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=qH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart

