#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
#Write a Bash script that configures a server to the above requirements

sudo apt-get update
sudo apt-get install nginx

mkdir -p /etc/nginx/html
printf '%s\n' "server {
    listen 80;
    listen [::]:80 default_server;

}" > /etc/nginx/sites-available/default

service nginx start