#!/usr/bin/env bash
#Using file #0;  Your Bash script must be 5 lines long or less

sudo apt-get update
sudo apt-get install -y nginx
echo -e "server {\n\tlisten 80;\n\tlisten [::]:80 default_server;\n}"
sudo service nginx restart