#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5 fizz for 3 buzz 5
for ((i=1;i<=100;i++))
do
    if ((i % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
